CREATE TABLE shop_history (
  id INT PRIMARY KEY AUTO_INCREMENT,
  account INT NOT NULL,
  player INT NOT NULL,
  date DATETIME NOT NULL,
  title VARCHAR(100) NOT NULL,
  cost INT NOT NULL,
  details VARCHAR(500) NOT NULL
) ENGINE = InnoDB DEFAULT CHARSET = utf8;
