ALTER TABLE `players`
  ADD COLUMN `skill_mining` INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN `skill_mining_tries` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `skill_woodcutting` INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN `skill_woodcutting_tries` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `skill_herbalism` INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN `skill_herbalism_tries` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `skill_crafting` INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN `skill_crafting_tries` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `skill_enchanting` INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN `skill_enchanting_tries` BIGINT UNSIGNED NOT NULL DEFAULT 0,
  ADD COLUMN `skill_disenchanting` INT UNSIGNED NOT NULL DEFAULT 10,
  ADD COLUMN `skill_disenchanting_tries` BIGINT UNSIGNED NOT NULL DEFAULT 0;
