blank_issues_enabled: false
contact_links:
- name: 📚 Documentation
  url: https://github.com/tibia-oce
  about: Check out the project documentation.
- name: 🤔 Questions
  url: https://discord.gg/TT2ebFwEyE
  about: Join our Discord community.
