version: "3.3"

services:
  database:
    container_name: database
    image: mariadb:latest
    restart: unless-stopped
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "/usr/bin/mysql", "--user=$$MARIADB_USERNAME",  "--password=$$MARIADB_ROOT_PASSWORD", "--execute", "SHOW DATABASES;"]
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 10
    env_file:
      - '../.env'
    networks:
      - database

  check-db-started:
    image: jwilder/dockerize:0.6.1    
    env_file:
      - '../.env'      
    depends_on:
      - database          
    command: 'dockerize -wait=tcp://database:3306 -timeout 30s'
    networks:
      - database

  application:
    container_name: application
    build:
      context: ..
      dockerfile: docker/Dockerfile
    ports:
      - 80:80
    env_file:
      - '../.env'
    networks:
      - database
    depends_on:
      check-db-started:
        condition: service_completed_successfully

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
    networks:
      - database
    ports:
      - 5001:80
    depends_on:
      check-db-started:
        condition: service_completed_successfully

  website:
    container_name: website
    image: ghcr.io/tibia-oce/website:0.8.19
    restart: unless-stopped
    env_file:
      - '../.env'
    networks:
      - database
    depends_on:
      - application
    ports:
      - 5002:80

volumes:
  database:

networks:
  database:
    driver: bridge
