name: Code Testing

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
    - main
    - master

jobs:
  go:
    name: Run Golang Tests
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        go-version: [1.16.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run tests
      run: go test ./...
