name: Commit Lint

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch the entire history
          fetch-depth: 0

      - name: Install dependencies
        run: npm ci --prefix .github/semantic-release

      - name: Get Commit Count
        run: echo "COMMIT_COUNT=$(git rev-list --count HEAD)" >> $GITHUB_ENV
      
      - name: Lint commit messages
        run: |
          RANGE=$((COMMIT_COUNT < 20 ? COMMIT_COUNT : 20))
          npx --prefix .github/semantic-release commitlint --config .github/semantic-release/commitlint.config.js --from=HEAD~${RANGE} --to=HEAD
      
