name: Commit Lint

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  commit-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm ci --prefix .github/semantic-release

      - name: Lint commit messages
        run: npx --prefix .github/semantic-release commitlint --from=HEAD~20 --to=HEAD
